const BatteryModel = require('../models/BatteryModel');
const SolarPanel = require('../models/SolarPanel');

const sampleBatteries = [
  {
    brand: 'Livguard',
    model: 'Solar Pro LFP 3.5k',
    chemistry: 'LiFePO4 (LFP)',
    capacity: 3.5,
    usableCapacity: 3.15,
    voltage: 48,
    roundTripEfficiency: 94,
    lifespanYears: 12,
    cycles: 5000,
    warrantyYears: 7,
    estimatedPrice: 85000,
    bestFor: 'Economy 2–4 Hour Essential Backup',
  },
  {
    brand: 'Luminous',
    model: 'LFP Powerpack 5.0',
    chemistry: 'LiFePO4 (LFP)',
    capacity: 5.0,
    usableCapacity: 4.5,
    voltage: 48,
    roundTripEfficiency: 95,
    lifespanYears: 15,
    cycles: 6000,
    warrantyYears: 10,
    estimatedPrice: 120000,
    bestFor: 'Standard Residential 4–6 Hour Backup & Self-Consumption',
  },
  {
    brand: 'Exide',
    model: 'Sunday LFP 7.5k',
    chemistry: 'LiFePO4 (LFP)',
    capacity: 7.5,
    usableCapacity: 6.75,
    voltage: 48,
    roundTripEfficiency: 94,
    lifespanYears: 14,
    cycles: 5500,
    warrantyYears: 10,
    estimatedPrice: 175000,
    bestFor: 'Medium Residential 6–8 Hour Backup & Peak Shaving',
  },
  {
    brand: 'Microtek',
    model: 'Solar Vault 10.0',
    chemistry: 'LiFePO4 (LFP)',
    capacity: 10.0,
    usableCapacity: 9.0,
    voltage: 51.2,
    roundTripEfficiency: 95,
    lifespanYears: 15,
    cycles: 6000,
    warrantyYears: 10,
    estimatedPrice: 220000,
    bestFor: 'Full Night Backup & High Reliability',
  },
  {
    brand: 'Reliance Solar',
    model: 'GigaPower LFP 5.0',
    chemistry: 'LiFePO4 (LFP)',
    capacity: 5.0,
    usableCapacity: 4.5,
    voltage: 48,
    roundTripEfficiency: 96,
    lifespanYears: 15,
    cycles: 6500,
    warrantyYears: 10,
    estimatedPrice: 110000,
    bestFor: 'High Efficiency & Great ROI',
  },
  {
    brand: 'Tesla',
    model: 'Powerwall 2',
    chemistry: 'NMC',
    capacity: 13.5,
    usableCapacity: 13.5,
    voltage: 50,
    roundTripEfficiency: 92,
    lifespanYears: 15,
    cycles: 5000,
    warrantyYears: 10,
    estimatedPrice: 450000,
    bestFor: 'Premium Whole-Home Off-Grid Backup',
  },
];

const samplePanels = [
  {
    brand: 'Tata Power Solar',
    model: 'TP-550W Mono PERC',
    cellTechnology: 'Monocrystalline PERC',
    efficiency: 21.3,
    power: 550,
    pricePerPanel: 16500,
    temperatureCoefficient: -0.36,
    warrantyProduct: 12,
    warrantyPerformance: 25,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 27.5,
    degradationRate: 0.55,
    country: 'India',
    bestFor: 'High Reliability & Strong Indian Brand Heritage',
  },
  {
    brand: 'Waaree Energies',
    model: 'Arka N-Type TOPCon 550W',
    cellTechnology: 'N-Type TOPCon',
    efficiency: 22.1,
    power: 550,
    pricePerPanel: 17200,
    temperatureCoefficient: -0.30,
    warrantyProduct: 12,
    warrantyPerformance: 30,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 27.2,
    degradationRate: 0.40,
    country: 'India',
    bestFor: 'Highest Efficiency & 30-Year Performance Warranty',
  },
  {
    brand: 'Adani Solar',
    model: 'Elan Shine 540W',
    cellTechnology: 'Monocrystalline PERC',
    efficiency: 21.1,
    power: 540,
    pricePerPanel: 15800,
    temperatureCoefficient: -0.35,
    warrantyProduct: 12,
    warrantyPerformance: 25,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 27.8,
    degradationRate: 0.55,
    country: 'India',
    bestFor: 'Best Value Indian Tier-1 Panel',
  },
  {
    brand: 'Vikram Solar',
    model: 'Somera Gran 550W',
    cellTechnology: 'Monocrystalline PERC',
    efficiency: 21.4,
    power: 550,
    pricePerPanel: 16200,
    temperatureCoefficient: -0.35,
    warrantyProduct: 12,
    warrantyPerformance: 25,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 27.5,
    degradationRate: 0.55,
    country: 'India',
    bestFor: 'Balanced Performance for Humid & Coastal Zones',
  },
  {
    brand: 'LONGi Solar',
    model: 'Hi-MO 6 Explorer 555W',
    cellTechnology: 'HPBC N-Type',
    efficiency: 22.5,
    power: 555,
    pricePerPanel: 18500,
    temperatureCoefficient: -0.29,
    warrantyProduct: 15,
    warrantyPerformance: 25,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 27.0,
    degradationRate: 0.40,
    country: 'Global',
    bestFor: 'Premium Global Sizing & Maximum Generation in Hot Climates',
  },
  {
    brand: 'JinkoSolar',
    model: 'Tiger Neo N-Type 560W',
    cellTechnology: 'N-Type TOPCon',
    efficiency: 22.3,
    power: 560,
    pricePerPanel: 18000,
    temperatureCoefficient: -0.30,
    warrantyProduct: 12,
    warrantyPerformance: 30,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 27.3,
    degradationRate: 0.40,
    country: 'Global',
    bestFor: 'Top Global Rated Power & High Yield',
  },
  {
    brand: 'RenewSys',
    model: 'DESERV Mono 540W',
    cellTechnology: 'Monocrystalline PERC',
    efficiency: 20.9,
    power: 540,
    pricePerPanel: 15200,
    temperatureCoefficient: -0.37,
    warrantyProduct: 10,
    warrantyPerformance: 25,
    dimensions: '2278 × 1134 × 35 mm',
    weight: 28.0,
    degradationRate: 0.60,
    country: 'India',
    bestFor: 'Lowest Upfront Cost & Budget Residential',
  },
];

const seedBatteriesAndPanels = async () => {
  try {
    const batteryCount = await BatteryModel.countDocuments();
    if (batteryCount === 0) {
      await BatteryModel.insertMany(sampleBatteries);
      console.log('✔ Seeded 6 Tier-1 Battery Storage models.');
    }

    const panelCount = await SolarPanel.countDocuments();
    if (panelCount === 0) {
      await SolarPanel.insertMany(samplePanels);
      console.log('✔ Seeded 7 Tier-1 Solar Panel models.');
    }
  } catch (err) {
    console.warn('DB seed for batteries and panels skipped/failed:', err.message);
  }
};

module.exports = {
  sampleBatteries,
  samplePanels,
  seedBatteriesAndPanels,
};
